if (CMAKE_BUILD_TYPE MATCHES "Debug")
    set(DebugCompilerFlags -Wall -Wextra -Wpedantic -g)
    message(STATUS "Target compiler flags are: ${DebugCompilerFlags}")
    add_compile_options(${DebugCompilerFlags})
elseif (CMAKE_BUILD_TYPE MATCHES "Release")
    set(DisabledCompilerFlags -Wno-return-type)
    message(STATUS "Target compiler flags are: ${DisabledCompilerFlags}")
    add_compile_options(${DisabledCompilerFlags})
endif()

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
